# Generated by Django 6.0.3 on 2026-03-27 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_admin_company_student'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationDate', models.DateField(auto_now_add=True)),
                ('applicationStatus', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REFUSED', 'Refused'), ('VALIDATED', 'Validated')], default='PENDING', max_length=10)),
                ('matchingScore', models.FloatField(default=0.0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='offers.internshipoffer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('topic', models.CharField(max_length=200)),
                ('supervisorName', models.CharField(max_length=200)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generationDate', models.DateField(auto_now_add=True)),
                ('pdfUrl', models.FileField(blank=True, null=True, upload_to='agreements/')),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('VALIDATED', 'Validated'), ('DOWNLOADED', 'Downloaded')], default='GENERATED', max_length=10)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='accounts.admin')),
                ('internship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='applications.internship')),
            ],
        ),
    ]
