# Generated by Django 6.0.3 on 2026-04-21 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_faculty_student_university'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('PENDING_CERT', 'Pending Certification'), ('COMPLETED', 'Completed')], default='ONGOING', max_length=15),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(default='VALIDATED', max_length=10),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueDate', models.DateField(auto_now_add=True)),
                ('pdfUrl', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='accounts.admin')),
                ('internship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='applications.internship')),
            ],
        ),
    ]
