# Generated by Django 6.0.3 on 2026-03-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('COMPANY', 'Company'), ('ADMIN', 'Admin')], max_length=10, null=True),
        ),
    ]
