# Generated by Django 6.0.3 on 2026-04-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='registreCommerce',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('IFA', 'Informatique Fondamentale et ses Applications'), ('MI', 'Mathématiques et Informatique'), ('TLSI', 'Technologies des Logiciels et Systèmes d’Information')], default='IFA', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='socialSecurityNumber',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='department',
            field=models.CharField(blank=True, choices=[('IFA', 'Informatique Fondamentale et ses Applications'), ('MI', 'Mathématiques et Informatique'), ('TLSI', 'Technologies des Logiciels et Systèmes d’Information')], max_length=10, null=True),
        ),
    ]
