# Generated by Django 6.0.3 on 2026-03-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_admin_company_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
