# Generated by Django 6.0.3 on 2026-04-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_registrecommerce_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registreCommerce',
            field=models.FileField(blank=True, null=True, upload_to='registres/'),
        ),
    ]
