# Generated by Django 6.0.3 on 2026-04-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_company_registrecommerce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='department',
            field=models.CharField(blank=True, choices=[('IFA', ' Informatiqe Fondamentale est ses Applications (IFA)'), ('MI', 'Mathématiques et Informatique (MI)'), ('TLSI', 'Technologie des logiciles et systémes informatiques  (TLSI)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('IFA', ' Informatiqe Fondamentale est ses Applications (IFA)'), ('MI', 'Mathématiques et Informatique (MI)'), ('TLSI', 'Technologie des logiciles et systémes informatiques  (TLSI)')], default='IFA', max_length=10),
        ),
    ]
