# Generated by Django 6.0.3 on 2026-03-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_phonenumber'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='students', to='offers.skill'),
        ),
    ]
