# Generated by Django 6.0.3 on 2026-04-17 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_admin_department_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='department',
            field=models.CharField(blank=True, choices=[('IFA', 'Informatique Fondamentale et ses Applications (IFA)'), ('MI', 'Mathématiques et Informatique (MI)'), ('TLSI', 'Technologies des Logiciels et Systèmes d’Information (TLSI)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('IFA', 'Informatique Fondamentale et ses Applications (IFA)'), ('MI', 'Mathématiques et Informatique (MI)'), ('TLSI', 'Technologies des Logiciels et Systèmes d’Information (TLSI)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
