# Generated by Django 6.0.3 on 2026-03-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
