# Generated by Django 6.0.3 on 2026-03-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_company_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isBlacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
