# Generated by Django 6.0.3 on 2026-03-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_company_isblacklisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logoUrl',
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='IDCardNumber',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
