# Generated by Django 6.0.3 on 2026-03-27 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_admin_company_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('willaya', models.CharField(max_length=100)),
                ('startingDay', models.DateField()),
                ('deadline', models.DateField()),
                ('type', models.CharField(choices=[('ONLINE', 'Online'), ('IN_PERSON', 'In Person')], max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='accounts.company')),
                ('requiredSkills', models.ManyToManyField(related_name='offers', to='offers.skill')),
            ],
        ),
    ]
