# Generated by Django 6.0.3 on 2026-04-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshipoffer',
            old_name='deadline',
            new_name='applicationDeadline',
        ),
        migrations.RenameField(
            model_name='internshipoffer',
            old_name='startingDay',
            new_name='internshipEndDate',
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='internshipStartDate',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='maxParticipants',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
