# Generated by Django 6.0.3 on 2026-04-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_rename_deadline_internshipoffer_applicationdeadline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshipoffer',
            options={'ordering': ['-id']},
        ),
    ]
